### ISSUE TITLE
Bounding boxes drawing cancels when drawing over the edge of an image

### ISSUE THREAD

**Issue by tobsecret** [SkalskiP/make-sense#10]
# Expected behaviour
When drawing a bounding box or other marker over the edge of an image, anything drawn over the edge clips to the edge.
# Observed behaviour
When drawing a bounding box over the edge of an image, the drawing cancels. This makes it more difficult to label objects in the periphery of images, which is frequently where they will be in microscopy images.

**Comment by SkalskiP** [comment]
@tobsecret Today I am starting to develop on this issue. I'll keep you posted on the progress.

**Comment by tobsecret** [comment]
Awesome, thank you!

**Comment by SkalskiP** [comment]
@tobsecret Snapping rectangles and points to the edges of the photo is now available in the developer version. If you have time to see the results of the work, you can test them on: https://develop.d2e9l8xwkaodsq.amplifyapp.com/

**Comment by tobsecret** [comment]
That looks awesome! Just how I thought it should be :ok_hand: 
When you make the polygon, it would also make sense for a newly drawn point to snap to the edges if drawn over the edge.

**Comment by SkalskiP** [comment]
Thanks, too, I think the new behavior is much better than the existing one. It is incomparable!
That is my plan - to maintain consistent behaviour for all types of labels. Polygon will be the most complicated so far, but I will try my best.
