### ISSUE TITLE
Load Files with Label Description - How does the label file have to be formatted? Please provide an Example File.

### ISSUE THREAD

**Issue by PUKL-XXXL** [SkalskiP/make-sense#100]
**Is your feature request related to a problem? Please describe.**

I would like to load previously defined Labels (which would be technically possible). Unfortunately I don't know how this input has to look like/be formatted.

**Describe the solution you'd like**

Please provide an example file.

**Describe alternatives you've considered**

-

**Additional context**

**Comment by SkalskiP** [comment]
Hi @PUKL-XXXL! That functionality is not yet added to MakeSense.

**Comment by SkalskiP** [comment]
This issue is duplicate of #32.
