### ISSUE TITLE
{[doubt] can I able to run make sense tool without internet on any browser?

### ISSUE THREAD

**Issue by angyee** [SkalskiP/make-sense#102]
I want to run this tool locally in my machine without the internet, I don't want to upload my data to the server o any, it is exactly like
a labeling tool? but added features? I want to write in python this tool, source code is opensource?

**Comment by SkalskiP** [comment]
1. MakeSense provides you with privacy. Images are not sent anywhere.
2. The code is OpenSource for purposes that are not for profit.
