### ISSUE TITLE
Suggest adding YOLOv5 labeller

### ISSUE THREAD

**Issue by glenn-jocher** [SkalskiP/make-sense#103]
Hi there! I'm updating the official YOLOv5 tutorials, and I wanted to guide people to the best open source labelling tools. I currently only mention Labelbox and CVAT, but I thought I might add this site. I wanted to ask you if any other tools come to mind that you know that would be suitable for YOLO labels?

Secondly, I saw you mentioned you use SSD for labelling, and I thought I'd reach out to encourage you to try YOLOv5. Our smallest and fastest model is 8MB, and reaches 36mAP@0.5:0.95, and our most accurate model is YOLOv5x at 49mAP@0.5:0.95, which is topping kaggle leaderboards when used for pseudo-labelling (which is what I think you are doing). 

If you have any questions, let me know!
https://github.com/ultralytics/yolov5

**Comment by SkalskiP** [comment]
Hi @glenn-jocher! As you may know, I am a big fan of your work and I would be delighted if MakeSense would be one of the suggested tools in your tutorials. As for the other labeling tools, I'm a little out of date, but at the moment nothing comes to mind :/

On the second subject. Is that model runnable in JavaScript environment?

**Comment by glenn-jocher** [comment]
@SkalskiP javascript probably not. Ah, I see the constraint now, of course. So your web solution is running the auto-labeling using user's local hardware? Of course, not sure why I didn't think of that before. Do you have any ideas on how to export from torch to javascript?

We currently have export to torchscript, coreml, onnx. Though to be honest the export pipelines are not super mature yet since the repo is pretty new.

**Comment by SkalskiP** [comment]
@glenn-jocher Exactly. It uses the customer's device and makes predictions in the browser. But I think we could join forces and do something cool! Hm... If you use ONNX maybe it would be possible to convert the model to TF and then to TF.js? Is it possible to go ONNX -> TF?

**Comment by glenn-jocher** [comment]
@SkalskiP ok, all set. I've added makesense.ai on our suggested labeling tools list, step 2. Does this look good?
https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

Yes, ONNX to TF should work, but we have been mostly focused on CoreML export as of late. I think next year we'd like to port our iDetection app over to Android as well, so we'll have to play the ONNX to TF game then ourselves, and we should have a better working export pipeline to TF :)

**Comment by SkalskiP** [comment]
Hi @glenn-jocher great thanks for the addition of makesense.ai to the list of tools. I clearly understand that you have your own backlog. But I am thrilled by the potential opportunity to work with you. Big fan of your repo.

**Comment by glenn-jocher** [comment]
@SkalskiP thanks! You seem to have a pretty good handle on web development. 

It would be nice to eventually trend YOLOv5 towards an AutoML style solution, with a web front end and a cloud backend with hosted datasets and training etc. Roboflow is a startup that seems to be doing a decent job of this already, using a subscription business plan. They're very small and just getting started, but their execution looks good.

**Comment by SkalskiP** [comment]
@glenn-jocher I worked for two years as a front engineer. Now I am working on CV on a daily basis, but there are still some skills left.

From what I see they are doing something similar to supervise.ly. I had such an idea for MakeSense once, but it is too big a project to create it on my own.

**Comment by glenn-jocher** [comment]
@SkalskiP yes I've seen supervisely. It's funny how they portray dataset augmentation as something you do once offline before training. Either they don't understand augmentation or their users don't, or both.

I was thinking of launching a fully end-to-end Saas service as well, a mixture of YOLOv5, Labelbox and Google's AutoML, plus edge deployment with iOS and Flutter reference apps, with cloud training, hosting and model serving. I think honestly a large fraction of the people arriving at our YOLO repos would much prefer this as well.

If you have some time perhaps we could chat and see if there may be a way to collaborate? You can use this link to schedule a meeting at a time that works for you if are interested!
https://calendly.com/ultralytics/meeting

**Comment by SkalskiP** [comment]
Hi, @glenn-jocher! They even build quite complicated functionalities around augmentation inside the platform. I have already set the meeting in the calendar. I'm always excited about the potential cooperation with you and your team! See you on Friday ;)
