### ISSUE TITLE
please share windows 10 installation instructions for makesense?

### ISSUE THREAD

**Issue by angyee** [SkalskiP/make-sense#104]

**Comment by MaskeZen** [comment]
The instructions are in the README: https://github.com/SkalskiP/make-sense#set-up-the-project-locally

you only need love... and [nodejs](https://nodejs.org/)

**Comment by SkalskiP** [comment]
Hi @angyee! Exactly as @MaskeZen  pointed out. All you need to set up MakeSense locally on windows is Node.js. Apart from that, all other instructions can be found in https://github.com/SkalskiP/make-sense#set-up-the-project-locally
