### ISSUE TITLE
Disable browser back buttons during labelling (to prevent data loss)

### ISSUE THREAD

**Issue by SteveCohen** [SkalskiP/make-sense#105]
**Is your feature request related to a problem? Please describe.**
Pressing 'back' button (or backspace key on some browsers) causes the browser to navigate back, as expected, which in turn causes all labelling work to be lost and unrecoverable. 

**Describe the solution you'd like**
Prompt the user whether the _really_ want to go 'back' (and lose their work) or halt. e.g. https://stackoverflow.com/questions/12381563/how-to-stop-browser-back-button-using-javascript

**Describe alternatives you've considered**
Alternatives are to save the work in some way, but given discussions about saving/reloading/persistent labelling, this seems harder to do than preventing back button. 

**Additional context**
Tested using Firefox v79 on Mac

**Comment by SkalskiP** [comment]
Hi @SteveCohen! Thank you very much for the idea. This feature should be in MakeSense from the beginning. I'll try to add it as soon as possible.

**Comment by SkalskiP** [comment]
@SteveCohen PR is up for review #106
