### ISSUE TITLE
Black Guidelines for Images with White Background

### ISSUE THREAD

**Issue by lester1027** [SkalskiP/make-sense#108]
Thank you very much for this amazing tool.

When I try to label images with a white background, the current white guidelines make me feel difficult to locate the cursor. Is it possible to add an option to change the guideline colour?

Thank you.

**Comment by SkalskiP** [comment]
Hi @lester1027! I was thinking about introducing a functionality that would choose whether the guidelines should be white or black, for example based on the colour of the pixel under the cursor.

**Comment by lester1027** [comment]
This is a good idea but I cannot tell if automation or manual selection is better for now.

**Comment by SkalskiP** [comment]
Hello @lester1027, I'm closing that issue as it is a duplicate of #124. However, we do not intend to swap this issue under the rug and if successful we will add it in the upcoming release.
