### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by devhci** [SkalskiP/make-sense#110]
**Describe the bug**
Failed to compile. I am trying to install  and run  brand new  setup without any changes 

**To Reproduce**
I am trying brand new install without any changes. 

**Expected behavior**
compile  
**Screenshots**
Find the attached screenshot 
<img width="1395" alt="Screenshot 2020-08-24 at 12 25 43" src="https://user-images.githubusercontent.com/3774356/91034505-6875d880-e605-11ea-8e04-8a23112b147f.png">

**Desktop (please complete the following information):**
 - OS: MAC 11
 - Browser chrome

**Comment by SkalskiP** [comment]
@devhci so what you have done is:

```bash
git clone https://github.com/SkalskiP/make-sense.git
cd make-sense
npm install
npm start
```

**Comment by devhci** [comment]
@SkalskiP  Yes. 

and I have  npm 6.14.5 and node.js  v14.5.0

**Comment by SkalskiP** [comment]
If possible, please switch to our supported environment: npm `6.x.x` and node.js `v11.x.x`.

**Comment by SkalskiP** [comment]
@devhci, also if possible please let us know if changing JS environment solved issue.

**Comment by SkalskiP** [comment]
@devhci any updates on that issue?
