### ISSUE TITLE
Not able to export mask

### ISSUE THREAD

**Issue by cmdrootaccess** [SkalskiP/make-sense#112]
Hello,

how do i export a mask using your service ? i am able to annotate but i can i cant export any image, only json formats.

i want to export something like this:

![1](https://user-images.githubusercontent.com/14039016/92127175-b65ebd80-ee09-11ea-9cb9-8c2989789fd5.jpg)
![1](https://user-images.githubusercontent.com/14039016/92127188-ba8adb00-ee09-11ea-8320-95fe2c213e90.png)

**Comment by SkalskiP** [comment]
Hello @cmdrootaccess, unfortunately at the moment, MakeSense does not yet have this possibility.

**Comment by Vozf** [comment]
I also think that adding this feature will be quite useful
