### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by kishore-jd** [SkalskiP/make-sense#116]

**Comment by kishore-jd** [comment]
how to integrate this application into my application ... please give me guidenece

**Comment by SkalskiP** [comment]
Hi @kishore-jd, could you give me more background on what kind of application you are building, what outcome you expect?

**Comment by kishore-jd** [comment]
We are Building medical application For Cervical cancer. i am using yolo v3
.i have one doubt how to able adjust bounding boxes after detection after
getting prediction.please reply me

**Comment by SkalskiP** [comment]
Hi @kishore-jd. I have two questions:
1. What do you mean to "adjust bounding boxes after detection" .
2. Where in all of that would you like to use MakeSense?

**Comment by kishore-jd** [comment]
yes  i want editable  of bounding boxes after  detection ..please help me as soon as posssible

**Comment by SkalskiP** [comment]
Editable bounding boxes are already part of MakeSense. Where is the problem?

**Comment by kishore-jd** [comment]
1)How to Work With My YOLO model To Achieve That Editable Functionality. My Model Build by using python..But Your Model is built by using typeScript. How Can I Achieve that one by our model?
2)At the last step in make sense how to export both file and images

**Comment by kishore-jd** [comment]
Hello ...i am waiting For Your Reply please ..

**Comment by SkalskiP** [comment]
Hi @kishore-jd:

1. What framework/library did you used to train your YOLO model? 
2. You can export annotations, but you will not be able to export images with it. We do not support this functionality.

**Comment by kishore-jd** [comment]
> Hi @kishore-jd:
> 
> 1. What framework/library did you used to train your YOLO model?
> 2. You can export annotations, but you will not be able to export images with it. We do not support this functionality.

>1.Darknet FrameWork

**Comment by kishore-jd** [comment]
open-cv library

**Comment by kishore-jd** [comment]
Hello Sir , I am Waiting For Your Reply

**Comment by SkalskiP** [comment]
Hi @kishore-jd. Unfortunately, your question is not about make-sense, but rather external libraries that we do not support.
