### ISSUE TITLE
Import in csv format

### ISSUE THREAD

**Issue by Claire1976** [SkalskiP/make-sense#125]
I would like to be able to:

- annotate
- then download and save
- then import my saved data back into Make Sense to continue annotating

all in .csv

your table suggests that csv importing is not yet a feature, but coming soon.  

How near are you to offering this as a feature?

**Comment by Claire1976** [comment]
....also, it'd be good to be able to import label pre-determined label data into the program at the start of the annotation, so I don't have to set that up every time I start a new annotation.

**Comment by SkalskiP** [comment]
Hi @Claire1976, cery noce to meet you. Please let me know wiat type of label would you like to import in csv format?

**Comment by SkalskiP** [comment]
As for importing labels list you can import it from file.
