### ISSUE TITLE
Shortcut keys?

### ISSUE THREAD

**Issue by JamesDevitt1** [SkalskiP/make-sense#126]
Great product!
Wondering if there any shortcut keys, specifically is there a shortcut to move to next image?  This would help me speed up my labeling.
Many thanks.

**Comment by ashutoshdhanda** [comment]
I just started using the app and I think it's just fantastic. The only thing that it lags, for my current workflow, is the inclusion of shortcuts keys. It could really use some, like move to the next image, previous, quick-select a class from the list, etc. Would make the task way more fluid.

Thanks and of course, keep up the good work. Clap-clap!

**Comment by SkalskiP** [comment]
@JamesDevitt1 and @ashutoshdhanda, you could use <kbd>Ctrl</kbd> + <kbd>Left</kbd> to go to previous and <kbd>Ctrl</kbd> + <kbd>Right</kbd> to go to next image.

**Comment by ashutoshdhanda** [comment]
@SkalskiP awesome!!

**Comment by SkalskiP** [comment]
In that case, I'm closing the issue ;)

**Comment by JamesDevitt1** [comment]
Great quick response.  Thanks.

**Comment by JamesDevitt1** [comment]
Hi Piotr,

Do you know if there is an alternative set of key shortcuts that work on
apple mac?

Many thanks,

Seamus

**Comment by SkalskiP** [comment]
Hi @JamesDevitt1. On mac you can use <kbd>⌥</kbd> + <kbd>Right</kbd> for next and <kbd>⌥</kbd> + <kbd>Left</kbd> for previous image. Aleso all of that is described in `README.md`.

## Supported Keyboard Shortcuts

| Functionality                      | Context  | Mac | Windows / Linux  |
|:-----------------------------------|:--------:|:---:|:----------------:|
| Polygon autocomplete               | Editor   | <kbd>Enter</kbd> | <kbd>Enter</kbd> |
| Cancel polygon drawing             | Editor   | <kbd>Escape</kbd> | <kbd>Escape</kbd> |
| Delete currently selected label    | Editor   | <kbd>Backspace</kbd> | <kbd>Delete</kbd> |
| Load previous image                | Editor   | <kbd>⌥</kbd> + <kbd>Left</kbd> | <kbd>Ctrl</kbd> + <kbd>Left</kbd> |
| Load next image                    | Editor   | <kbd>⌥</kbd> + <kbd>Right</kbd> | <kbd>Ctrl</kbd> + <kbd>Right</kbd> |
| Zoom in                            | Editor   | <kbd>⌥</kbd> + <kbd>+</kbd> | <kbd>Ctrl</kbd> + <kbd>+</kbd> |
| Zoom out                           | Editor   | <kbd>⌥</kbd> + <kbd>-</kbd> | <kbd>Ctrl</kbd> + <kbd>-</kbd> |
| Move image                         | Editor   | <kbd>Up</kbd> / <kbd>Down</kbd> / <kbd>Left</kbd> / <kbd>Right</kbd> | <kbd>Up</kbd> / <kbd>Down</kbd> / <kbd>Left</kbd> / <kbd>Right</kbd> |
| Exit popup                         | Popup    | <kbd>Escape</kbd> | <kbd>Escape</kbd> |

**Comment by JamesDevitt1** [comment]
Perfect.  Thanks again.

**Comment by SkalskiP** [comment]
No problem :)
