### ISSUE TITLE
typescript error: 

### ISSUE THREAD

**Issue by pepijnob** [SkalskiP/make-sense#127]
Hi I'm trying to run make-sense locally on windows 10 using npm. 
After running 'npm start' I got a, '=' expected.  TS1005 error, after some googling I found that I had to update typescript and change it in the package.json file, after reinstalling I got a different error:
"
TypeScript error in C:/Windows/System32/make-sense/src/logic/render/LineRenderEngine.ts(210,24):
Argument of type '{ type: Action; payload: { firstLabelCreatedFlag: boolean; }; }' is not assignable to parameter of type 'UpdateActiveImageIndex | UpdateActiveLabelNameId | UpdateActiveLabelId | UpdateHighlightedLabelId | ... 19 more ... | UpdateDisabledAIFlag'.
  Type '{ type: Action; payload: { firstLabelCreatedFlag: boolean; }; }' is not assignable to type 'UpdateDisabledAIFlag'.  TS2345

    208 |         imageData.labelLines.push(labelLine);
    209 |         store.dispatch(updateImageDataById(imageData.id, imageData));
  > 210 |         store.dispatch(updateFirstLabelCreatedFlag(true));
        |                        ^
    211 |         store.dispatch(updateActiveLabelId(labelLine.id));
    212 |         this.lineCreationStartPoint = null
    213 |         EditorActions.setViewPortActionsDisabledStatus(false);
"
Any suggestion on how I could fix this? or shouldn't I have updated typescript in the first place?
Thank you in advance,

Pepijn

**Comment by SkalskiP** [comment]
@pepijnob no I guess you shouldn't have. :) Please go back to the default `package.json` and provide the error that you see with our version of TS. Also, let us know what version of `node` and `npm` you have on your Windows machine?

**Comment by pepijnob** [comment]
@SkalskiP Thanks for the fast reply,
I have npm version 6.14.8 and node version 12.19.0.
I changed it back to the package.json file and after 'npm start' this is the error shown (first I see the app on my browser for 1 sec):
"
TypeScript error in C:/Windows/System32/make-sense/node_modules/jest-diff/build/diffLines.d.ts(8,13):
'=' expected.  TS1005

     6 |  */
     7 | import { Diff } from './cleanupSemantic';
  >  8 | import type { DiffOptions } from './types';
       |             ^
     9 | export declare const diffLinesUnified: (aLines: Array<string>, bLines: Array<string>, options?: DiffOptions | undefined) => string;
    10 | export declare const diffLinesUnified2: (aLinesDisplay: Array<string>, bLinesDisplay: Array<string>, aLinesCompare: Array<string>, bLinesCompare: Array<string>, options?: DiffOptions | undefined) => string;
    11 | export declare const diffLinesRaw: (aLines: Array<string>, bLines: Array<string>) => Array<Diff>;
"

**Comment by SkalskiP** [comment]
Let's start by changing your `node` version and make it the same as the one we support:  `v11.x.x`.

**Comment by SkalskiP** [comment]
@pepijnob any updates on that?

**Comment by pepijnob** [comment]
@SkalskiP Hi , thanks. I installed v11.10.1. I deleted the files that were there and ran the process from start again. Right now I get the error:
"
\make-sense>npm install
npm WARN make-sense@1.0.0 No description
npm WARN make-sense@1.0.0 No repository field.

up to date in 0.381s

\make-sense>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     \AppData\Roaming\npm-cache\_logs\2020-10-26T10_51_03_776Z-debug.log
"

However, I think this has to do with my companies proxy. As an other example was working fine with version 12 but not anymore. I'm looking into this myself atm. any suggestions?

**Comment by SkalskiP** [comment]
Hm... I don't think it is an issue with companies proxy. 

1. Could you do`ls` or `dir` (depending on os you use) in `make-sense` dir?
2. Could you do `git status` in `make-sense` dir?

**Comment by pepijnob** [comment]
dir:

10/26/2020  10:23 AM    <DIR>          .
10/26/2020  10:23 AM    <DIR>          ..
10/26/2020  10:23 AM    <DIR>          .github
10/26/2020  10:23 AM               290 .gitignore
10/26/2020  10:23 AM               154 .travis.yml
10/26/2020  10:23 AM    <DIR>          docker
10/26/2020  10:23 AM    <DIR>          examples
10/26/2020  10:23 AM            35,823 LICENSE
10/26/2020  10:23 AM           665,719 package-lock.json
10/26/2020  10:23 AM             1,861 package.json
10/26/2020  10:23 AM    <DIR>          public
10/26/2020  10:23 AM             9,320 README.md
10/26/2020  10:23 AM    <DIR>          src
10/26/2020  10:23 AM               763 tsconfig.json
               7 File(s)        713,930 bytes
               7 Dir(s)  114,180,042,752 bytes free


Git status:

On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean


package.json:

{
  "name": "make-sense",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^4.1.1",
    "@tensorflow-models/coco-ssd": "^2.0.0",
    "@tensorflow-models/posenet": "^2.1.3",
    "@tensorflow/tfjs": "^1.2.9",
    "@types/jest": "24.0.14",
    "@types/node": "12.0.8",
    "@types/react": "16.8.20",
    "@types/react-dom": "16.8.4",
    "classnames": "^2.2.6",
    "file-saver": "^2.0.2",
    "jszip": "^3.2.2",
    "lodash": "^4.17.20",
    "mobile-detect": "^1.4.3",
    "moment": "^2.24.0",
    "node-sass": "^4.14.1",
    "react": "^16.8.6",
    "react-custom-scrollbars": "^4.2.1",
    "react-dom": "^16.8.6",
    "react-dropzone": "^10.1.5",
    "react-redux": "^7.1.0",
    "react-scripts": "^3.4.3",
    "react-spinners": "^0.9.0",
    "redux": "^4.0.4",
    "typescript": "3.5.2",
    "uuid": "^3.3.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "CI=true react-scripts test --env=./src/__test__/custom-test-env.js",
    "test:coverage": "npm test -- --coverage",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/classnames": "^2.2.8",
    "@types/file-saver": "^2.0.1",
    "@types/jszip": "^3.1.6",
    "@types/lodash": "^4.14.135",
    "@types/moment": "^2.13.0",
    "@types/react-custom-scrollbars": "^4.0.5",
    "@types/react-dropzone": "^4.2.2",
    "@types/react-redux": "^7.1.0",
    "@types/uuid": "^3.4.4",
    "prettier": "^1.17.1",
    "redux-devtools": "^3.5.0"
  }
}

**Comment by SkalskiP** [comment]
@pepijnob I see no `node_modules` in your `dir` result. Am I correct?

**Comment by pepijnob** [comment]
@SkalskiP yes

**Comment by SkalskiP** [comment]
@pepijnob please execute `npm install` in `make-sense` dir, and paste here:

**Comment by pepijnob** [comment]
>npm install
npm WARN make-sense@1.0.0 No description
npm WARN make-sense@1.0.0 No repository field.

up to date in 0.387s

**Comment by SkalskiP** [comment]
@pepijnob this is all you get in terminal?

**Comment by pepijnob** [comment]
@SkalskiP yes, that's all

**Comment by SkalskiP** [comment]
Overall the problem is that your npm does not create the `node_modules` directory during `npm install`. So when you run `npm start` you do not have the required script. It is not the fault of MakeSense but your configuration I guess.

**Comment by pepijnob** [comment]
Okay, good to know and thanks for all the help. I will have a further look into this
