### ISSUE TITLE
Exporting annotations to Pascal VOC XML

### ISSUE THREAD

**Issue by OlafenwaMoses** [SkalskiP/make-sense#13]
First, this is a very remarkable project and I am looking forward to it making significant improvement in the image annotation experience.

It will be great if support for exporting annotated data to **Pascal VOC** XML can be provided. See the links below for example blueprint of the format.

https://gist.github.com/Prasad9/30900b0ef1375cc7385f4d85135fdb44

https://github.com/AndrewCarterUK/pascal-voc-writer/blob/master/pascal_voc_writer/templates/annotation.xml

There is an existing **non-UI** tool that does that. You can take insights from it to implement the UI based annotation. See the link below for the tool.

https://github.com/AndrewCarterUK/pascal-voc-writer/blob/master/pascal_voc_writer/templates/annotation.xml

**Comment by SkalskiP** [comment]
Thank you very much for your kind words. I will try to make sure that the enormous potential of this project will be used. The task seems pretty simple. However, I am wondering about the values in the fields: folder, path and database. They can hardly be hardcoded, they must be received from the user?

**Comment by OlafenwaMoses** [comment]
The **folder**, **path** and **database** are **meta data** of the annotation. 

- **folder**: This is used to identify the folder in which an image is present on the system in which the annotation was performed. Considering your's run in-browser You can generate a value here based on the title for their project.
- **path**: This is the full path of the image on the system. You can just specify the filename here
- **database**: This is just a reference data. You can keep it as value `unknown`

**Comment by SkalskiP** [comment]
Then the path and the database are clear. As for the folder - at the moment the user does not define the name of the project, in this situation it is worth to define something like this?

**Comment by SkalskiP** [comment]
I'm gonna work on this task now.

**Comment by OlafenwaMoses** [comment]
> Then the path and the database are clear. As for the folder - at the moment the user does not define the name of the project, in this situation it is worth to define something like this?

Since it is a meta data, you can use a default value for the folder property.

**Comment by SkalskiP** [comment]
I decided to put in the top navigation bar input, where you can define the name of the project. Perhaps this functionality will be useful in other situations.

**Comment by SkalskiP** [comment]
@OlafenwaMoses The functionality is already on the develop version. It will come with the next release. It can be tested on a test instance: https://develop.d2e9l8xwkaodsq.amplifyapp.com/

**Comment by OlafenwaMoses** [comment]
Great work you have done on this @SkalskiP . I just tested it and the experience is great.

**Comment by OlafenwaMoses** [comment]
Make sure to promote this tool via tutorials on Medium as well.

**Comment by SkalskiP** [comment]
I am very happy that everything works as expected. If you have any more ideas on how to improve makesense.ai, I encourage you to create issues. As I said, the functionality will be in the application with the next realase. This should be soon, but I do not have any rigid date.

As for the tutorial on the Medium, you don't have to persuade me. I haven't written in a long time and I would love to change it. I hope that I will find time in the coming days.

**Comment by hadilou** [comment]
Hi @SkalskiP . Thanks for the great work. I have enjoying the tool lately :)

I want to point out that [truncated](https://github.com/AndrewCarterUK/pascal-voc-writer/blob/e41bea5b2edcd8021fe585395e5cb6b272a1626b/pascal_voc_writer/templates/annotation.xml#L17) and  [difficult](https://github.com/AndrewCarterUK/pascal-voc-writer/blob/e41bea5b2edcd8021fe585395e5cb6b272a1626b/pascal_voc_writer/templates/annotation.xml#L18) attribute should be boolean i.e 0 by default not "unknown".  

I had to make these modification to saved Pascal VOC labels in other to open them in tools such as [labelImg](https://github.com/tzutalin/labelImg)
