### ISSUE TITLE
Parsing error when importing labels in yolo format

### ISSUE THREAD

**Issue by wesje97** [SkalskiP/make-sense#130]
Hi,

Currently when trying to reimport the yolo files in makesense to continue the labeling we are running into some random parsing errors.

**Comment by SkalskiP** [comment]
Hi, @wesje97. Could you provide some more info? maybe provide an example of a file that is causing problems?

**Comment by WesleyW97** [comment]
Hi, @SkalskiP . Ofcourse. I have added an example image I used for the labeling, the labels.txt file and the output of the yolo format I got after exporting the annotations.


[20200528-locH1-iPhone8.txt](https://github.com/SkalskiP/make-sense/files/5505213/20200528-locH1-iPhone8.txt)

[labels.txt](https://github.com/SkalskiP/make-sense/files/5505216/labels.txt)


![20200528-locH1-iPhone8](https://user-images.githubusercontent.com/54795799/98447855-67dedf80-2128-11eb-9766-d3276d8dfb11.jpg)

**Comment by SkalskiP** [comment]
Hi, @WesleyW97! Thank you very much for provideing examples. I was able to sucesfully truck down the bug. Fix is already on https://www.makesense.ai/. @wesje97 and @WesleyW97, please let me know if you will still experience those issues in future.
