### ISSUE TITLE
Import darknet (aka YOLO) format annotations fails when image/label filenames contain multiple "." characters

### ISSUE THREAD

**Issue by ecounce3** [SkalskiP/make-sense#140]
**Describe the bug**
I have image files and annotations in a format such as "DSC_0023.mp4#t=22.png" and "DSC_0023.mp4#t=22.txt".  Importing these existing annotations fails with an error message "Given predicate results in more than one value being matched".  

**To Reproduce**
1. select Import Annotations
2. select Multiple Files in YOLO Format
3. Select multiple annotation files in format "DSC_0000.mp4#t=0.txt"
4. Import fails with error "Given predicate results in more than one value being matched"

**Expected behavior**

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 87
 - Version develop/HEAD (afc138d)

**Additional context**
This appears to be the result YOLOImporter.matchImagesWithAnnotations using FileUtils.extractFilename which returns index 0 after splitting the filename on dot (".").  
A proposed fix is extractFilename to return path.basename(name, path.extname(name)) instead of name.split(".")[0]

**Comment by SkalskiP** [comment]
@ecounce3 Thank you for pointing out this problem. I have checked and I understand the source of the issue. We will try to eliminate it as soon as possible. It should be relatively simple.
