### ISSUE TITLE
Per-class coloration

### ISSUE THREAD

**Issue by flocreate** [SkalskiP/make-sense#141]
Hi there, realy great tool. 

I am testing this tool for multi-class object detection.
Would it be possible to select a color per class (label) so one can visualize what box corresponds to what label. This will help avoid selecting a wrong label for a box.

I think a color is a nice and easy way to do this. But a custom icon placed over/near the box could also be realy cool (eventualy with an option to show/hide and avoid bloking the edition).

**Comment by SkalskiP** [comment]
Hi @flocreate, I apologize for not responding. A lot of work not related to MakeSense. The idea seems interesting and actually simple to implement.

**Comment by SkalskiP** [comment]
Hi @flocreate, I started to work on this issue: https://github.com/SkalskiP/make-sense/pull/190. However, I still have a lot to go. I will let you know about the progress.
