### ISSUE TITLE
Import labeled images progress

### ISSUE THREAD

**Issue by slobodaapl** [SkalskiP/make-sense#147]
Currently, the 'import annotations' in the action menu actually imports labels for images. I mistakenly thought it actually imports data of already annotated parts of images.

It would be nice that I can import a YOLO file generate by Make Sense to resume where I last left off. It would read the labels from the first column, and the rectangle positions from the rest and assign them to the respective image based on its name, and add it to the rectangle list of annotations for each respective image.

**Comment by SkalskiP** [comment]
Hi @slobodaapl, importing YOLO annotations from the last session is already possible inside MakeSense. It doesn't work for you?

**Comment by slobodaapl** [comment]
I see, no it doesn't work and I'm not sure why.

When I click 'import annotations' and drag and drop the labels.txt in YOLO format outputted by Image Sense into the website, it loads the file, but no actual annotations appear on the right side.. No rectangles appear over the images.

Instead, I've noticed that it creates a lot of labels, as in classes, with each line from the .txt file as an individual label

**Comment by SkalskiP** [comment]
Are you dragging only `labels.txt`? Or you also drop other `.txt` files along with it?

**Comment by SkalskiP** [comment]
@slobodaapl I just tested that feature, and it works. In that case, I would like to ask you to supply me with:
* your `labels.txt` file
* single image from your dataset
* single annotations `.txt` file corresponding with that image
I'll try to take a look at you r problem.

**Comment by slobodaapl** [comment]
I have identified the problem, it is not on your side.

I am running a lot of JS modifying scripts and browser-side packet sniffers and traffic shapers, and I found it has
modified something on the website to make the file damaged/process it incorrectly.

**Comment by SkalskiP** [comment]
Ok. So glad to see that everything is working properly on the MakeSense side.

**Comment by panban-ux** [comment]
I currently have annotated txt files with corresponded pictures made from other software and i want to import those annotations as label.txt by drag and drop or import. It doesn't seem to show those annotations or load them. I use the local host Makesence in firefox. Any imputs or i miss something?
