### ISSUE TITLE
Windows 10 Requires normalize.css!

### ISSUE THREAD

**Issue by mmortazavi** [SkalskiP/make-sense#16]
Thanks for the great tool; well-done, and I will be looking forward to trying out new features. 

One note for Windows 10 Users. After following the instructions and successfully installing the make-sense I couldn't view it in the browser (e.g. Google Chrome). Basically `npm start` in Windows 10 Ubuntu results in the following error in the browser:

Error: Cannot find module '@csstools/normalize.css' nodejs

Although the message is self-explanatory, but I was struggling a bit since I have had zero experience with Node.js. Finally I figured one need to install `normalize.css` simply: 
`npm install normalize.css`

Maybe it is best that README to be updated.
And you are good to go, Happy labelling!!

**Comment by SkalskiP** [comment]
@mmortazavi For clarity, you're talking here about running locally on Windows 10 by the Ubuntu bash console?

Thanks a lot for the information, I admit that the whole application has been developed so far on Linux and Mac, and so far, on Windows 10, we were running only the online version.

**Comment by mmortazavi** [comment]
> @mmortazavi For clarity, you're talking here about running locally on Windows 10 by the Ubuntu bash console?

Yes, exactly.

> 
> Thanks a lot for the information, I admit that the whole application has been developed so far on Linux and Mac, and so far, on Windows 10, we were running only the online version.

Noted. Thanks for sharing your work.

**Comment by SkalskiP** [comment]
@mmortazavi Great, I understand everything. In this situation, I will put an appropriate note in README.md. As I understand, simple `npm install normalize.css --save` is all you need to solve the problem?

**Comment by mmortazavi** [comment]
Well, you know when you wanna make something work you try different things. The only step that was preceded before `npm install normalize.css --save` was to upgrade npm to the latest, whether it was relevant, I am not sure (your judgement, I found out about upgrading in another project repo):

`npm install -g npm@latest` 

And restarted the system for changes to be effective, somewhere it was suggested!

**Comment by SkalskiP** [comment]
Sure, I've been in a situation like this more than once or twice. In my opinion `npm install normalize.css --save` addition should be enough. Once again, thank you very much for drawing attention to these problems!

**Comment by SkalskiP** [comment]
The information has been added to [README.md][1] in the develop version and will appear in the master with the next releas. It's visible in the section: Set Up the Project Locally.

[1]: https://github.com/SkalskiP/make-sense/blob/develop/README.md

**Comment by yyuuliang** [comment]
hi
can u give the local environmental setting? I installed npm and try to run, still have the same error
Cannot find module '@csstools/normalize.css'

**Comment by mmortazavi** [comment]
Did you install `npm install normalize.css --save` as well?

**Comment by SkalskiP** [comment]
@yyuuliang In your case, does this problem occur on Windows or Linux? 

My settings I work with:
OS: Linux Mint 19.1 Tessa
brawser: Chrome 72
npm: 6.7.0
node: v11.10.1

**Comment by nieszkodzi** [comment]
Now I updated node to v12.10.0 and npm to 6.10.3, delete all repo, cloned it again, made all instructions one more time and it's working :)

**Comment by SkalskiP** [comment]
I'm very pleased to hear that! Then add to README the information that such versions are required to ensure proper local operation.

**Comment by SkalskiP** [comment]
I have added a new description to README, in this situation I am closing the issue again.
