### ISSUE TITLE
Invalid YOLO annotations exported for bboxes on the edge of an image

### ISSUE THREAD

**Issue by wvierber** [SkalskiP/make-sense#171]
**Describe the bug**
When bounding boxes align with an edge of the image, it often occurs that invalid YOLO annotations are exported. This gives an error when annotations are imported in other tools, e.g. [albumentations](https://github.com/albumentations-team/albumentations).

Example on a 1920x1080 image for y_max:
- For reference, bounding box as exported in csv format: `[444, 998, 90, 82]`
- Bounding box as exported in YOLO format: `[0.254728, 0.961913, 0.046957, 0.076175]`
- YOLO to image coordinates for y_max: `y + h/2 = 0.961913 + 0.076175/2 = 1.0000005`

Another example for x_max:
- For reference, bounding box as exported in csv format: `[1828, 710, 92, 104]`
- Bounding box as exported in YOLO format: `[0.976042, 0.705556, 0.047917, 0.096296]`
- YOLO to image coordinates for x_max: `x + w/2 = 0.976042 + 0.047917/2 = 1.0000005`

Another example I bounced into for x_min:
- For reference, bounding box as exported in csv format: `[0, 138, 80, 70]`
- Bounding box as exported in YOLO format: `[0.020833, 0.160185, 0.041667, 0.064815]`
- YOLO to image coordinates for x_max: `x - w/2 = 0.020833 - 0.041667/2 = -0.0000005`

**To Reproduce**
Export annotations in YOLO format of bounding boxes that have an edge on the edge of the image.

**Expected behavior**
YOLO annotations should not result in values outside [0,1] when they are converted.
Following assertions should always be true for exported annotations:
```
x - w/2 > 0
x + w/2 < 1
y - h/2 > 0
y + h/2 < 1
```

**Desktop (please complete the following information):**
Version 1.7.0-alpha relese

**Comment by SkalskiP** [comment]
Hi @wvierber! I've worked on that issue over the weekend. After the changes, YOLO export will produce the following results:
- For `[444, 998, 90, 82]` -> `[0.254688 0.962037 0.046875 0.075926]`, where `0.962037 + 0.075926/2 = 1.0`
- For `[1828, 710, 92, 104]` -> `[0.976042, 0.705556, 0.047916, 0.096296]`, where `0.976042 + 0.047916/2 = 1.0`
- For `[0, 138, 80, 70]` -> `[0.020833, 0.160185, 0.041666, 0.064815]`, where `0.020833 - 0.041666/2 = 0.0`

Changes are not yet on https://www.makesense.ai/ (they will be in few weeks - after the next release), but you can test and use it on our test instance https://develop.makesense.ai/.

Would be great if you could test it and let me know if everything works.

**Comment by SkalskiP** [comment]
I am closing the issue. Solved.
