### ISSUE TITLE
is this make sense AI a fully self hosted solution ?

### ISSUE THREAD

**Issue by jimbot10** [SkalskiP/make-sense#18]
is this make sense AI a fully self hosted solution i.e. it can all be run locally?

Thanks

**Comment by SkalskiP** [comment]
Hi, @jimbot10  yes, that's right. You can use Make Sense in two ways:
- Online: on https://makesense.ai
- Offline: Starting the application according to the following instructions:

```
# clone repository
git clone https://github.com/SkalskiP/make-sense.git

# navigate to main dir
cd make-sense

# install dependencies
npm install

# serve with hot reload at localhost:3000
npm start
```

**Comment by jimbot10** [comment]
Thanks, good stuff.
