### ISSUE TITLE
What's the format of the label.txt?

### ISSUE THREAD

**Issue by MM629** [SkalskiP/make-sense#200]
Makesense.ai requires a label.txt when I import annotations.

So whats the format about label.txt, I think this file is use to tell mankesense.ai how many labels are there and whats their name.

Thank You Very Much

**Comment by SkalskiP** [comment]
Hello 👋 , @MM629. Your hunch is correct. `label.txt` file contains a list o class names, where each class name is defined in a new line. For example: 

```
cat
dog
hedgehog
```

**Comment by SkalskiP** [comment]
I'm cloasing this issue as solved :)
