### ISSUE TITLE
Installation on Mac M1 taking forever

### ISSUE THREAD

**Issue by vahuja4** [SkalskiP/make-sense#206]
The title states it. My internet speed is 30 Mbps download, so that is not the problem. It is just taking forever to install make-sense on my Mac M1.

**Comment by SkalskiP** [comment]
Hi @vahuja4👋  ! I'm really sorry to hear that. Unfortunately, I'm not using Mac M1. But I'll try to reach out to my friends and try to run some tests.

**Comment by rasyidf** [comment]
It might be because of tensorflow.js need to compile into binary.

i found some tricky step in [stackoverflow](https://stackoverflow.com/questions/66462857/tensorflow-js-error-on-mac-os-11-with-m1-chip)

Steps to use it with tfjs-node in mac m1

- Download libtensorflow from the link https://drive.google.com/file/d/1zo59yNayVtewvOXvFG-pSy2Jgrcqwkj4/view?usp=sharing
- Copy to <YOUR_PROJECT>//node_modules/@tensorflow/tfjs-node/deps and unzip it.
- Replace the contents with existing contents in the folder.

**Comment by SkalskiP** [comment]
@vahuja4 could you take a look at the solution proposed by @rasyidf?

**Comment by jack-bgl** [comment]
Error when installing, using Apple M1 MacBook pro. Seems to relate to Tensorflow?

```
_npm notice 
npm notice New minor version of npm available! 8.3.1 -> 8.6.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.6.0
npm notice Run npm install -g npm@8.6.0 to update!
npm notice 
npm ERR! code 1
npm ERR! path /Users/jzhang/Documents/Projects/make-sense/node_modules/@tensorflow/tfjs-node
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! CPU-darwin-3.9.0.tar.gz
npm ERR! * Downloading libtensorflow
npm ERR! /Users/jzhang/Documents/Projects/make-sense/node_modules/@tensorflow/tfjs-node/scripts/install.js:103
npm ERR!     throw new Error(`Unsupported system: ${libType}-${platform}-${os.arch()}`);
npm ERR!           ^
npm ERR! 
npm ERR! Error: Unsupported system: cpu-darwin-arm64
npm ERR!     at getPlatformLibtensorflowUri (/Users/jzhang/Documents/Projects/make-sense/node_modules/@tensorflow/tfjs-node/scripts/install.js:103:11)
npm ERR!     at downloadLibtensorflow (/Users/jzhang/Documents/Projects/make-sense/node_modules/@tensorflow/tfjs-node/scripts/install.js:136:15)
npm ERR!     at async run (/Users/jzhang/Documents/Projects/make-sense/node_modules/@tensorflow/tfjs-node/scripts/install.js:205:5)_
```

**Comment by SkalskiP** [comment]
Hello, @jack-bgl 👋 ! Unfortunately, I do not have M1 MacBook Pro at my disposal, but I'm happy to cooperate with you in fixing that issue. First of all, did you try the solution proposed by @rasyidf above?

**Comment by SkalskiP** [comment]
Hello, @jack-bgl 👋 ! Unfortunately, I do not have M1 MacBook Pro at my disposal, but I'm happy to cooperate with you in fixing that issue. First of all, did you try the solution proposed by @rasyidf above?

**Comment by SkalskiP** [comment]
Hi @vahuja4, @jack-bgl and @rasyidf I have MacBook with M1 now. I installed make-sense locally without any problems. For that reason I'm closing this issue. If similar problems will happen once again in the future we will of course reopen :)
