### ISSUE TITLE
Feature Request :  Statistics

### ISSUE THREAD

**Issue by rasyidf** [SkalskiP/make-sense#209]
**Is your feature request related to a problem? Please describe.**
Addings some statistics of project would be great to make it easier to report (academically, perhaps).

something like (not sorted but would be great to be added):

- [ ] Images Status-> (Missing / Corrupted, Blurred, Rejected, Succeed ) 
- [ ] Class Ballance -> Under Represented, Over Represented.
- [ ] Annotation -> Count, Average, Class Represented, Heatmap
- [ ] Image -> Average Size, Range, Aspect Ratio Distribution, Dimension 

**Describe the solution you'd like**
It's somehow too much, but some of it would be great addition to app.

**Comment by SkalskiP** [comment]
Hello, again @rasyidf 👋  isn't that a duplication of #76?

**Comment by rasyidf** [comment]
ouch that's my bad, I'll move it there. and close this
