### ISSUE TITLE
Textual labels converted into numeric labels on export

### ISSUE THREAD

**Issue by Jaster111** [SkalskiP/make-sense#216]
**Describe the bug**
Exporting the labels turns them into numeric values. For example, if you had labels ("Road", "Bridge", "Grass") it turns them to ("0", "1", "2"). This is a bug I have recently encountered, for sure it didn't always act like that.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by SkalskiP** [comment]
Hello @Jaster111 👋 ! What export type are you using?

**Comment by Jaster111** [comment]
Hi @SkalskiP ! I am exporting as a zip package containing files in YOLO format, using the bounding box technique. Don't know if I have suddenly started doing something wrong or did something else change.

**Comment by SkalskiP** [comment]
@Jaster111 so the problem is that you are getting labels in this format:

```
1 0.716797 0.395833 0.216406 0.147222
0 0.687109 0.379167 0.255469 0.158333
1 0.420312 0.395833 0.140625 0.166667
```

Where the first column is the class.

**Comment by Jaster111** [comment]
@SkalskiP that is exactly the problem.

**Comment by SkalskiP** [comment]
Oh, so in that case, it is not a bug. It is exactly as intended. That is how YOLO label format is structured. Take a look at this [article](https://towardsdatascience.com/image-data-labelling-and-annotation-everything-you-need-to-know-86ede6c684b1).
