### ISSUE TITLE
Annotation timestamp

### ISSUE THREAD

**Issue by albertotestoni** [SkalskiP/make-sense#217]
Hi! I am setting up an annotation experiment using your makesense platform. That's a super great and useful tool, thanks for developing it! 👏 I am interested in both object detection and image classification tasks. I would like to save a timestamp for each annotation (for example, in the object segmentation task I would like to get a timestamp for **each** bounding box). Is it possible to get this information in makesense? I know I do not get this information when I export the annotation.. I was wondering whether there is an easy way to get it. Thanks a lot for your help!

**Comment by SkalskiP** [comment]
Hello @albertotestoni 👋  ! Thank you very much for your question and interest in our project. Unfortunately, no. At this time, we do not store information about the creation date of the label. We don't have that on our roadmap either.
