### ISSUE TITLE
How is this application different from other opensource applications?

### ISSUE THREAD

**Issue by TheDeathConqueror** [SkalskiP/make-sense#23]
I'm the user of another opensource image labeling application https://github.com/NaturalIntelligence/imglab.

I noticed that the number of stars to your application are increasing every day quickly. But I found that this application is the kind of subpart of https://imglab.in (feature-wise). So am I missing something? or do we need to put the effort to create another image labeling tool?

**Comment by SkalskiP** [comment]
@TheDeathConqueror  In my opinion, the appearance of a tool that does something similar in a different way is always beneficial. It makes us all try to improve what we have created and take inspiration from it. The imglab is an interesting tool that does many things well.

You're absolutely right, at the moment - makesense.ai has fewer feathers than, for example, imglab. It's worth remembering, however, that from what I checked, imglab is a project that started in Oct 2017, **makesense.ai is only 2 months old**. If you give us some time, I think that many feathers, which are missing, will be available.

makesense.ai - aims to optimize and simplify the labeling process. While testing the imglab, I noticed that many of the actions it wants to perform require a lot of clicks and are not intuitive. By multiplying it hundreds or thousands of photos, you're wasting time and effort. **I think it attracts people to our tool. They can see that we try to make the process as simple as possible for them.**

Additionally makesense.ai plans to introduce many feathers that are not available in imglab or other open source tools.

For what tasks do you use imglab?

**Comment by TheDeathConqueror** [comment]
I use it for one of my projects. I didn't understand the part you mentioned about multiple clicks. Because as I remember, I used the mouse to create the labels only. Rest I controlled from the keyboard.

Though I'm not the right person to comment, but I thought that the combined effort from both authors would have result something better.
