### ISSUE TITLE
Annotation Import Unsuccessful: Unexpected error occured duriong parsing of 2710.jpg annotation file

### ISSUE THREAD

**Issue by blackShine-2** [SkalskiP/make-sense#241]
I followed the steps mentioned in issue #222. I successfully edited more than 1000 the annotation files too.  But, now I am getting this error. Please look at this.
![image](https://user-images.githubusercontent.com/95059200/164608366-699ce45c-7dd0-4400-98e9-632ae1a9cf8c.png)

**Comment by SkalskiP** [comment]
Hello @blackShine-2 👋 ! I’m sorry to hear that. I’ll try to help you out, but I’ll need your image and annotation file to do that. I’s it possible that you share those with me?

**Comment by blackShine-2** [comment]
> Hello @blackShine-2 👋 ! I’m sorry to hear that. I’ll try to help you out, but I’ll need your image and annotation file to do that. I’s it possible that you share those with me?

I have emailed you in _[piotr.skalski92@gmail.com](mailto:piotr.skalski92@gmail.com)_ from _blackshinepc@gmail.com_. Please find it.

**Comment by SkalskiP** [comment]
Hi, @blackShine-2! I got your email. I'll try to take a look at it today 🧐

**Comment by SkalskiP** [comment]
Hi, @blackShine-2! I got your email. I'll try to take a look at it today 🧐

**Comment by SkalskiP** [comment]
Okay, so I've done some debugging and I know what is the problem.

This is the content of the `2710.txt` label file:

```txt
0 0.504580 0.495252 0.990840 0.930991
1 0.385999 0.832067 0.473667 0.148465
43 0.230291 0.836815 0.035329 0.050332
46 0.268400 0.842830 0.036964 0.054131
5 0.309127 0.845362 0.041871 0.056664
45 0.377821 0.848528 0.040563 0.052865
43 0.422800 0.850902 0.049395 0.060146
44 0.466143 0.853435 0.032712 0.052548
42 0.514393 0.851060 0.036310 0.050332
77 0.480061 0.603321 0.960121 0.630996
```

The last entry of that file is a box with a class index equal to `77`. This is a problem because according to your `labels.txt` file you have only 65 classes.

Did you manually edited `2710.txt` or `labels.txt` file?

**Comment by SkalskiP** [comment]
Okay, so I've done some debugging and I know what is the problem.

This is the content of the `2710.txt` label file:

```txt
0 0.504580 0.495252 0.990840 0.930991
1 0.385999 0.832067 0.473667 0.148465
43 0.230291 0.836815 0.035329 0.050332
46 0.268400 0.842830 0.036964 0.054131
5 0.309127 0.845362 0.041871 0.056664
45 0.377821 0.848528 0.040563 0.052865
43 0.422800 0.850902 0.049395 0.060146
44 0.466143 0.853435 0.032712 0.052548
42 0.514393 0.851060 0.036310 0.050332
77 0.480061 0.603321 0.960121 0.630996
```

The last entry of that file is a box with a class index equal to `77`. This is a problem because according to your `labels.txt` file you have only 65 classes.

Did you manually edited `2710.txt` or `labels.txt` file?

**Comment by blackShine-2** [comment]
Okay. Thank You so much. May be the labelled files are mis-matched.

**Comment by SkalskiP** [comment]
No problem. I think it would make sense to give users slightly more information. About the accounting problem. I'll try to improve that process in the future.

**Comment by SkalskiP** [comment]
No problem. I think it would make sense to give users slightly more information. About the accounting problem. I'll try to improve that process in the future.

**Comment by blackShine-2** [comment]
> No problem. I think it would make sense to give users slightly more information. About the accounting problem. I'll try to improve that process in the future.

Thank You.
