### ISSUE TITLE
no shortkey support for faster work?

### ISSUE THREAD

**Issue by Petros626** [SkalskiP/make-sense#248]

**Comment by SkalskiP** [comment]
@Petros626 could you help me out here. Do you mean keyboard shortcats? Those are listed in project `README.md`.

**Comment by Petros626** [comment]
Hey,

yeah I dismiss to read it, but this helps. The ML automation will work after activaiton on it's own without any further key shortcut?

**Comment by SkalskiP** [comment]
What do you mean by `ML automation`?

**Comment by Petros626** [comment]
> What do you mean by `ML automation`?

the ssd for generating suggestions, it's pretrained algorithm and not a new learning by marking some object now

**Comment by SkalskiP** [comment]
That is true. We only support pre-trained models for now.
