### ISSUE TITLE
add headers for exported csv file

### ISSUE THREAD

**Issue by sadegh-pz** [SkalskiP/make-sense#252]
It isn't easy to locate xmin, ymin, xmax, and ymax values from the exported CSV file as it doesn't have headers.

I want that when I export using a CSV file, I get a file with headers.

**Comment by SadeghPouriyanZadeh** [comment]
Hi @SkalskiP 
Thank you so so much for considering this issue and making changes. I've checked it at the development web app; it was awesome. Now I can use this fast, simple, and adorable app for my annotations. 
Now I close this issue here. Thanks again.

**Comment by SkalskiP** [comment]
No problem @SadeghPouriyanZadeh! Exporting labels via CSV file is not very popular, and that's why that functionality is not as polished as I'd want it to be. All in all, it's great that we could use this opportunity to make it just a little bit better.
