### ISSUE TITLE
wrong values from exported csv file and showed rectangular bbox

### ISSUE THREAD

**Issue by SadeghPouriyanZadeh** [SkalskiP/make-sense#253]
here we see that I select two points:

first [5, 10]

![Screenshot (4)](https://user-images.githubusercontent.com/74629673/172594365-694faa88-6b90-4517-aa4d-5ff626581c2b.png)

second [140, 40]

![Screenshot (5)](https://user-images.githubusercontent.com/74629673/172594518-998e7168-aba9-47cc-990d-9b319f81aff3.png)

but exported CSV file saves different values!

![Screenshot (6)](https://user-images.githubusercontent.com/74629673/172594693-e57234f7-202b-43a5-8048-98d8f92df356.png)

What is the problem?

**Comment by SkalskiP** [comment]
Hi, @SadeghPouriyanZadeh 👋 ! Here are the headers for the result CSV file columns:
`label_name, x, y, width, height, image_name, image_width, image_height`. I know it is not really obvious without headers. But given that information, you can see that for example `135` is simply the result of subtracting `140` and `5`.

**Comment by SadeghPouriyanZadeh** [comment]
Thanks, now it's clear.
It would be helpful for others who have this problem know that x and y are top left corner.
Thank you, @SkalskiP, for your detailed explanation.
