### ISSUE TITLE
Importing Annotations for keeping progress (COCO JSON)

### ISSUE THREAD

**Issue by DanielJBernard** [SkalskiP/make-sense#256]
I noticed that one problem with this AI was I could export a COCO file as one JSON file with the current annotations on the images I had already completed. However, it seems you can't import that progress at least with COCO JSON Files which is the only type I tested. None of my annotations or the images that I annotated would show up when attempting an import. This was a slight problem because this means if I had hundreds of images to annotate, I would have to keep my progress by keeping my browser open for days depending on the workload for a project. Luckily this did not effect me that much considering my workload was not in the hundreds but for others that maybe are using this AI to annotate within that range of images, this would be very frustrating.

**Comment by SkalskiP** [comment]
Hi, @DanielJBernard this is really weird... we support COCO JSON import. Could you share with me the COCO JSON file that you are trying to import as well as one or more images that you already labeled?

**Comment by SkalskiP** [comment]
Great to hear that everything works now! 🚀 In case any new problems would accrue, please let me know!
