### ISSUE TITLE
Support for YOLOv5 P6 Models

### ISSUE THREAD

**Issue by JohannaSopraSteria** [SkalskiP/make-sense#281]
Hi! First and foremost, thanks for adding support for YOLOv5 models 😃

 For my project I am using a [YOLOv5 P6](https://github.com/ultralytics/yolov5/issues/2110) model. When I try to upload this model in the specified format I get this error message:
![image](https://user-images.githubusercontent.com/114214074/195039725-b74c659c-7a6e-441d-95c7-ac4b700828bd.png)

It seems that so far Make Sense, only accepts the original YOLOv5 P3-P5, as this works fine when I upload such a model. Would it be possible for you to extend this so that YOLOv5 P6 models also can be used to annotate images?

**Comment by SkalskiP** [comment]
Hi, @JohannaSopraSteria 👋! Thanks for letting me know. From what I can see the model fails during inference, not model loading. 

First of all, I need to replicate the error. Which weights are you using precisely? `yolov5s6`?

**Comment by JohannaSopraSteria** [comment]
Correct, I'm using `yolov5s6`

**Comment by SkalskiP** [comment]
I just tested `yolov5s6`. I converted it to tensorflow.js format `python export.py --weights yolov5s6.pt --include tfjs` and it worked. 

So I think there might be another reason. Do you use a custom model (your own, trained on some custom dataset)?

**Comment by SkalskiP** [comment]
@JohannaSopraSteria could you share with me over email or here, your model along with the `txt` file containing class names?

**Comment by JohannaSopraSteria** [comment]
@SkalskiP I've shared the file with you via mail.

**Comment by SkalskiP** [comment]
Hello @JohannaSopraSteria! I'm afraid I haven't got anything. :(

**Comment by SkalskiP** [comment]
I have it. It was in spam. Let me take a look :)

**Comment by SkalskiP** [comment]
@JohannaSopraSteria I know what seems to be the problem - input resolution. I hardcoded the input resolution `640`, as it was working for all the models I tested. Your model requires `1280` for some reason. Now I need to think about how to fix it.

- Hardcode it as `1280` - the problem is that the inference will be slower for other YOLOv5 models.
- Allow the user to select resolution. Will take me some time to do it right. Not to mention that you could still select the incorrect one.
- Try to detect if the model requires a larger input resolution somehow.

**Comment by SkalskiP** [comment]
Hi @JohannaSopraSteria! I guess I managed to fix model loading problems. Please take a look at [this](https://feature-282-confusion-around-ui-for-uploading-labels.d2e9l8xwkaodsq.amplifyapp.com) test version of Make Sense and let me know if it works :)

**Comment by JohannaSopraSteria** [comment]
Hi @SkalskiP :) Unfortunately I still get the "Inference failed" message :/ I'm still using the same model I sent you.

**Comment by SkalskiP** [comment]
Oh sorry, @JohannaSopraSteria it looks like I screwed up links... 

Please take a look here: https://fix-281-support-for-yolov5-p6-models.d2e9l8xwkaodsq.amplifyapp.com/

**Comment by JohannaSopraSteria** [comment]
Works perfectly 😁 Well done @SkalskiP !

**Comment by SkalskiP** [comment]
This is great @JohannaSopraSteria! 🎉 I'm really happy we got it to work! Thank you very much for bringing that problem to my attention. 

We are not yet ready to release the new version of Make Sense. So for now you can access the fixed editor here: https://develop.makesense.ai. It is our test instance.
