### ISSUE TITLE
Confusion around UI for uploading labels

### ISSUE THREAD

**Issue by JohannaSopraSteria** [SkalskiP/make-sense#282]
After uploading images, I try to upload my labels.txt file. Once I have selected/dropped it I cannot simply select "Create labels list" nor "Start project" to get started.

The only way I found to use these labels is to select these buttons in the given order:

1. `Start project`
2. `Create labels list` (labels appear in "Create labels" pane)
3. `Start project`

This works, but is quite unintuitive for a new user. To recreate this, I am using COCO images and the corresponding COCO labels.txt file.

![image](https://user-images.githubusercontent.com/114214074/195315041-cae3fb0c-c390-4ae4-8db7-cab93f4bb341.png)

**Comment by SkalskiP** [comment]
Hi @JohannaSopraSteria! Thank you very much for bringing that to my attention. That one should be easy to fix.

**Comment by SkalskiP** [comment]
@JohannaSopraSteria take a look [here](https://feature-282-confusion-around-ui-for-uploading-labels.d2e9l8xwkaodsq.amplifyapp.com) - it is a test version of makesense.ai with fixed uploading labels popup. Let me know if everything works. If so, then we will merge it.

**Comment by JohannaSopraSteria** [comment]
@SkalskiP This works great if I press  `Start project` after uploading the files, but if I press `Create labels list` I loose the labels I just uploaded. Still a bit unintuitive for me 😅
![image](https://user-images.githubusercontent.com/114214074/195342362-286c368b-1102-43e5-a8ec-8b8e6fd1b274.png)

**Comment by SkalskiP** [comment]
Honestly, that part of Make Sense is really confusing to me. :) Apologies for that.

I 100% agree it would be great if you would not lose the list of labels that you just uploaded when you go from one popup to the other. Problem is that it is technically hard as those popups do not communicate with each other.

This is my proposal for now: 
- Merge the proposed change as the current behavior is obviously a bug. 
- Keep that issue for now as I want to redesign the whole flow for label list definition. I'm not really sure how long that will take as I have a few other things on my plate.

**Comment by JohannaSopraSteria** [comment]
@SkalskiP Perhaps you could just change the text on the "Create labels list" button to "Go back". That way a user will know that they will return to the previous popup and loose their current list, which really is what happens.

**Comment by SkalskiP** [comment]
Sure! Take a look here: https://feature-282-confusion-around-ui-for-uploading-labels.d2e9l8xwkaodsq.amplifyapp.com/ it is updated.

**Comment by JohannaSopraSteria** [comment]
Looks like this to me now:
![image](https://user-images.githubusercontent.com/114214074/195536913-28509ba6-6013-4341-8274-f0a1cbc5579c.png)
Is this updated?

**Comment by SkalskiP** [comment]
@JohannaSopraSteria sorry it did not rebuild automatically for some reason. I did it manually. You can take a look.

**Comment by JohannaSopraSteria** [comment]
@SkalskiP Looks good! 👍

**Comment by SkalskiP** [comment]
Great! So I'm merging that to develop, and similarly to https://github.com/SkalskiP/make-sense/issues/281, in the near future, those changes will be available at https://develop.makesense.ai/.

As I said earlier. I fully intend to redesign the label names definition popups, but I have at least one new feature to finish before I do that.
