### ISSUE TITLE
labels

### ISSUE THREAD

**Issue by Aurora1-max** [SkalskiP/make-sense#286]
hello,i want to load a label file from my computer but failed,which called me that file has no label.why is it?

**Comment by Aurora1-max** [comment]
Actually,my label file has 17 labels,but it reminds me " 0 labels".

**Comment by SkalskiP** [comment]
Hello, @Aurora1-max 👋! Thank you very much for your interest in Make Sense! I'm happy to help you out with that :) Could you upload your labels file here or send it to me over email?

**Comment by Aurora1-max** [comment]
No problem,Just like the following example:
//
ribbon_butterfly
Chinese_big_flat_spade
Chinese_elephant_wax_cicada
two_tailed_nymphal
cloud_spotted_white_striped_beetle
human_striped_lampworm
beautiful_moss_moth
oriental_arborvitae_moth
light_shouldered_star_beetle
lunar_scallop_moth
thorn_shouldered_predestined_stinkbug
Double_cedar_beetle
color_night_moth
//
  I used the "_" to separate my labels everylines.
![1111](https://user-images.githubusercontent.com/81025651/196856568-0f095eb8-a9c8-4477-9eb5-0c4a6bfac69c.jpg)

**Comment by Aurora1-max** [comment]
> Hello, @Aurora1-max 👋! Thank you very much for your interest in Make Sense! I'm happy to help you out with that :) Could you upload your labels file here or send it to me over email?

In addition,i have accomplished some label task before by this way,but i don't know why it doesn't work recently

**Comment by SkalskiP** [comment]
Hi, @Aurora1-max 👋! Could you just drag and drop the actual file into the comment here? :) It should allow you to just upload the whole file. Maybe there is something wrong with the actual file or some very unusual interaction with it, but it would be much, much easier for me to find it with actual file. 🙏

**Comment by Aurora1-max** [comment]
Oh,sorry,it's my fault.
[label.txt](https://github.com/SkalskiP/make-sense/files/9826712/label.txt)
It suddenly dawned on me. Maybe I have imported too many tags at one time, as many as 97. This is probably the reason, because I just tried fewer tags and it succeeded.

**Comment by SkalskiP** [comment]
@Aurora1-max No worries. I tested and managed to replicate the error. I need to take care of few things first. But I'll try to debug it today. :)

**Comment by Aurora1-max** [comment]
Very thanks !!

**Comment by SkalskiP** [comment]
Hi, @Aurora1-max 👋! I figured it out :) So the main problem is that your `labels.txt` file contains non-unique label names. It is not allowed, and that's why makesense.ai does not allow you to load.

On the other hand, I am definitely not satisfied with the way we handled the error. We should have simply said what the issue was so that the user could fix the problem on their own. For this reason, I have made some changes to the application.

I deployed a test version of the app with changes here: https://feature-286-not-unique-class-names-handling.d2e9l8xwkaodsq.amplifyapp.com. It would be great if you could test if communication is more intuitive now.

**Comment by Aurora1-max** [comment]
@SkalskiP  Yeah,that's cool.Thank you. I found the problem. I just tested it with the demo you provided and got a reminder. It's a great improvement. I will make good use of it and earnestly promote "Makesense" for you. Give the thumbs-up!!

**Comment by SkalskiP** [comment]
@Aurora1-max I'm so happy you like it! And I'm super happy we made makesense.ai better today. 🚀 🎉

So just to wrap everything up. I just merged https://github.com/SkalskiP/make-sense/pull/288, into `develop`. This means that you will be able to access this and other unreleased features at develop.makesense.ai. It will stay there until the next release, which should come in a few weeks. Then it will be officially at makesense.ai. Until then please use develop version. ;)
