### ISSUE TITLE
Docker fails to build

### ISSUE THREAD

**Issue by montmejat** [SkalskiP/make-sense#289]
**Describe the bug**
The Docker image fails to build.

```
$ docker build -t make_sense docker/
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM node:14.18.0
 ---> 8cf18d365a37
Step 2/5 : RUN apt-get update && apt-get -y install git && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> d1f3b0fb94db
Step 3/5 : RUN mkdir /workspace &&   cd /workspace &&   git clone https://github.com/SkalskiP/make-sense.git &&   cd make-sense &&   npm install
 ---> Running in c3a61b2da2b8
Cloning into 'make-sense'...
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for esbuild-linux-arm64@0.14.49: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  arm64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-26T09_35_26_519Z-debug.log
The command '/bin/sh -c mkdir /workspace &&   cd /workspace &&   git clone https://github.com/SkalskiP/make-sense.git &&   cd make-sense &&   npm install' returned a non-zero code: 1

```

**To Reproduce**
`docker build -t make_sense docker/`

**Expected behavior**
It builds without any errors :smile: 

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by montmejat** [comment]
Building works when updating the Dockerfile with `FROM node:16.18.0`. However, I get "Unable to connect" in Firefox when connecting to IP:3000.

I have also tried:
```
$ npm install 
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@vitejs/plugin-react@2.0.0',
npm WARN EBADENGINE   required: { node: '>=14.18.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'vite@3.0.2',
npm WARN EBADENGINE   required: { node: '^14.18.0 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

up to date, audited 753 packages in 2s

107 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ npm start

> make-sense@1.0.0 start
> vite

file:///home/aurelien/Projects/GitHub/make-sense/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

I have the following versions:
```
$ npm -v
8.5.1
$ node -v
v12.22.9
```

**Comment by SkalskiP** [comment]
Hi, @aurelien-m 👋 It looks like our Dockerfile and instructions are heavily outdated. 😱 Let me quickly fix that.

**Comment by SkalskiP** [comment]
@aurelien-m sorry it took me so long. My changes are right now in the `develop` branch. Please try to test if it works for you. Make sure you follow the updated instructions in `README.md`.

**Comment by montmejat** [comment]
@SkalskiP Thanks! No worries, it was not urgent for me, it works perfectly now.

I might have missed it but it doesn't look like Make Sense has an API or SDK of some sort? It would be nice to have one to be able to create projects and pre-annotate images in our custom pipelines.

I also have a suggestion, it's a bit slow for our (quite strange) use case. We're labeling very tiny objects (~ 50 px in size) in very big images (5k images). So we need to be able to zoom in more than what's possible and zoom in where the cursor is pointing. The scrolling is a bit slow when I tried it, we can gain more time and have less headaches if it's smooth :smile:

**Comment by SkalskiP** [comment]
> it works perfectly now

@aurelien-m I'm glad that the problem was solved relatively quickly!

> I might have missed it, but it doesn't look like Make Sense has an API or SDK of some sort. It would be nice to have one to be able to create projects and pre-annotate images in our custom pipelines.

You can use YOLOv5 models to annotate images in Make Sense. Would that be helpful?

> So we need to be able to zoom in more than what's possible and zoom in where the cursor is pointing.

We can increase max zoom if you want to.

> The scrolling is a bit slow when I tried it

That is weird. Could you share with me an image example so that I could test it out on my machine?

**Comment by montmejat** [comment]
I can't share any of our images, but this one is a pretty good example (6000 x 4000 pixels) of what we have:

![pexels-irina-iriser-1379636](https://user-images.githubusercontent.com/29719028/198239830-007bc044-0d97-437c-96da-206002d35e72.jpg)

Here's a comparison between Make Sense and Label Studio (even though the best would be to try it out yourself):

[Screencast from 10-27-2022 10 50 53 AM.webm](https://user-images.githubusercontent.com/29719028/198239671-04290ea7-aff2-42ae-b80c-e77bb9a62b93.webm)

[Screencast from 10-27-2022 10 49 32 AM.webm](https://user-images.githubusercontent.com/29719028/198239783-d821311f-280c-41f4-aa59-ffd1fa75f2af.webm)

The experience is much smoother in Label Studio, and the directed scrolling with the mouse is a really great feature! Please let me know if you have the same experience.

Regarding YOLOv5, it could help us, but we would need to be able to use our own model trained on our data. We have data pipelines that process incoming data and automatically build annotation projects from them. Meaning that you can log into the app, and quickly begin annotating and verifying the automatic annotations. That's why I'm asking.

**Comment by SkalskiP** [comment]
> The experience is much smoother in Label Studio, and the directed scrolling with the mouse is a really great feature! Please let me know if you have the same experience.

This part of the editor was written quite a long time ago, and indeed it leaves much to be desired. For a long time I have been thinking of rewriting this functionality, but so far the community rarely reported problems, so I focused on other tasks. **One thing in particular that annoys me is that the zoom does not take place in the direction of the cursor, but rather towards the center of the photo. Well, and of course, I can see the lag, which makes it difficult to work with the image at high zoom.** 😔

Could you file a bug report on this? It would help me to keep track of this topic. Well, and hopefully I can find time to work on it.

> Regarding YOLOv5, it could help us, but we would need to be able to use our own model trained on our data.

You can upload your own pre train model. You just drag and drop model files into editor and use it to infer on images. Taka a look at this video for more details:

https://user-images.githubusercontent.com/26109316/193255987-2d01c549-48c3-41ae-87e9-e1b378968966.mov

**Comment by montmejat** [comment]
@SkalskiP Thanks for the video explanation and taking the time to reply! I'll open an issue today. I've also got a long 4-days week-end coming, I might take a look at the code :smile:

**Comment by SkalskiP** [comment]
@aurelien-m sure! I'm always excited when people try to use makesense.ai. :D I know it is not perfect, but I'm surely trying to make it as good as possible.

**Comment by domagojhack** [comment]
Hi, I am trying to install make-sense locally however after running `npm start` I am getting the following error.

```
$ npm start

> make-sense@1.11.0-alpha start
> vite --port 3000

file:///home/domagoj/github/make-sense/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```
I see that @aurelien-m  had similar issues but it seems it shouldn't happen again.

My npm is `8.5.1` and my nodejs version is `v12.22.9`.

**Comment by SkalskiP** [comment]
@DomagojHack, is that happening in our docker container?

**Comment by domagojhack** [comment]
no docker installation instructions are not working for me at all. I know this is a docker related issue but [https://github.com/SkalskiP/make-sense/issues/289#issuecomment-1291778609](https://github.com/SkalskiP/make-sense/issues/289#issuecomment-1291778609) suggested to install it using npm, and I am not keen about using docker on my setup.

**Comment by SkalskiP** [comment]
What's the setup?

**Comment by domagojhack** [comment]
Freshlly installed Ubuntu 22.04 LTS. All requirements are already installed.

**Comment by SkalskiP** [comment]
> no docker installation instructions are not working for me at all.

Can I ask why?
