### ISSUE TITLE
how do i get a labels.txt file to import annotations?

### ISSUE THREAD

**Issue by abhavgoel** [SkalskiP/make-sense#323]
i am trying to import annotations of a existing dataset and make some changes in it , how can i import it. it says need a labels.txt file..how do i create it and what to enter in it?

**Comment by SkalskiP** [comment]
Hi @abhavgoel 👋🏻 ! Nice to see you here. Take a look at this issue: https://github.com/SkalskiP/make-sense/issues/222. You should find all the information you need here. I'm closing this issue as it is a duplicate. However, feel free to reopen it if you'll need more help.
