### ISSUE TITLE
annotation import was unsuccessful 

### ISSUE THREAD

**Issue by AouatifZ** [SkalskiP/make-sense#326]
Hello everyone, 
 

I have a problem loading images and annotations in Make Sense,

Error --->  unexpected error occurs during parsing of image annotations file:

here's an example of my annotation 

Example----> 
2 0.809375 0.577604 0.110156 0.261458 
3 0.601337 0.285813 0.080579 0.172176 
2 0.679332 0.319559 0.052686 0.112948 
0 0.400407 0.629477 0.120868 0.245179 
1 0.207225 0.583333 0.133264 0.378788 
2 0.081708 0.561983 0.076446 0.088154 

any suggestion , what's the problem 

thanks in advance

**Comment by alexHxun** [comment]
same problem , can not import .txt file even i import the labels.txt with correct content

**Comment by AouatifZ** [comment]
I've found the solution: the labels files must respect the structure requested by MakeSense, i.e. labels.txt must not contain a space at the end of each bounding box in labels.txt, and also the last BB recorded in the file must not make a line break, to avoid any problems with the format and structure requested.

I hope this information helps solve your problem.

**Comment by SkalskiP** [comment]
Hi, @AouatifZ and @alexHxun 👋🏻! It seems that these changes should be simple to implement. Would you like me to remove these artificial restrictions related to whitespace characters?
