### ISSUE TITLE
zoom and pan image to see object clearly

### ISSUE THREAD

**Issue by sagar-g-v** [SkalskiP/make-sense#33]
-add option to zoom in and out of image
-this will help in creating more accurate annotation

**Comment by SkalskiP** [comment]
I totally agree. This is one of the features that are at the forefront of what I want to introduce. You can expect to see the zoom feature in the editor in the near future. Thanks so much for making an issue about this.

**Comment by SkalskiP** [comment]
Hi @sagar-g-v! Zoom in/out has been added to makeense.ai! For now it is available on the developer instance - https://develop.makesense.ai/, but soon it will be possible to use this option also on the production. Happy labelling!

**Comment by Bucephalus-lgtm** [comment]
Can MAX_ZOOM not be increased until 10 or 12? Only 4times bigger picture makes it hard for the annotator to annotate the images.

**Comment by SkalskiP** [comment]
Hi, @Bucephalus-lgtm 👋 I don't think there should be any problem with that. I honestly don't remember why we decided to use 4.

**Comment by Bucephalus-lgtm** [comment]
In general there is not much of any problem but in case you are to annotate rice from a pile of rices, it's hard with 4times zoom. For example, look at the following image:
![Uploading IMG_20220807_153206838~2.jpg…]()

**Comment by Bucephalus-lgtm** [comment]
![IMG_20220807_153234236_2 (1)](https://user-images.githubusercontent.com/57415694/183840516-75ab0c75-0af6-44a8-989c-134d91f32a9d.jpg)

**Comment by SkalskiP** [comment]
🤯 it really looks like a lot of work! I'll try to add this change tonight. I just need to make sure that it wont break anything.
