### ISSUE TITLE
web page isn't working?

### ISSUE THREAD

**Issue by ghost** [SkalskiP/make-sense#332]

**Comment by MatokoAI** [comment]
same here.

**Comment by UAV-T1** [comment]
same here    Display network connection issues

**Comment by guiklos** [comment]
Same here it displays a DNS_PROBE_POSSIBLE error

**Comment by ch-hristov** [comment]
Perhaps the domain is no longer maintained?

**Comment by KetannChandra** [comment]
Not working for me either.

**Comment by ghost** [comment]
> Perhaps the domain is no longer maintained?

probably

**Comment by KetannChandra** [comment]
any free open source online alternatives to makesense.ai?

**Comment by ghost** [comment]
> any free open source online alternatives to makesense.ai?

you can run it locally,it's quite easy

**Comment by SkalskiP** [comment]
Hi @k00r, @MatokoAI, @UAV-T1, @guiklos and @KetannChandra 👋🏻!

I'm sorry. I have already taken the appropriate steps. And I hope that makesense.ai will return online as early as today.

I will let you know in this issue and on [Twitter](https://twitter.com/skalskip92) :)

**Comment by SkalskiP** [comment]
@k00r, @MatokoAI, @UAV-T1, @guiklos and @KetannChandra makesense.ai is online! 

![Screenshot 2023-07-17 at 13 15 21](https://github.com/SkalskiP/make-sense/assets/26109316/79ac5c28-86a5-4828-81d6-ccfd174f856e)

**Comment by MatokoAI** [comment]
thanks for your help. Really appreciated

**Comment by SkalskiP** [comment]
Unfortunately, I don't have time to add new features. But I can at least make sure it is online.

**Comment by ghost** [comment]
> Unfortunately, I don't have time to add new features. But I can at least make sure it is online.

thank you and no problem,it's quite amazing as it is,maybe i will ^___^

**Comment by SkalskiP** [comment]
> maybe i will ^___^

You will... have time to write new Make Sense features?

**Comment by ghost** [comment]
> > maybe i will ^___^
> 
> You will... have time to write new Make Sense features?

thing is i'm using make sense heavily and i already have a few ideas which can be implemented as new features or improve upon existing ones

**Comment by SkalskiP** [comment]
> I'm using make sense heavily

I love to hear that!

> I already have a few ideas which can be implemented as new features or improve upon existing ones.

I'd love to read about it.

**Comment by ghost** [comment]
> > I'm using make sense heavily
> 
> I love to hear that!
> 
> > I already have a few ideas which can be implemented as new features or improve upon existing ones.
> 
> I'd love to read about it.

i've sent you an e-mail
