### ISSUE TITLE
If there is only points annotation, the exported csv contains nothing.

### ISSUE THREAD

**Issue by yyuuliang** [SkalskiP/make-sense#36]
**Describe the bug**
I load an image, make points annotation, then export the csv file. There is nothing inside the csv file.
I then draw a bounding box on the same image, then export the points. This time the csv file contains the points locations.

**To Reproduce**
1. Load an image
2. make some points annotations
3. export the points to a csv file

**Expected behavior**
The csv file should contains points locations even if there is no bounding box.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Ubuntu 16
 - Browser: Chrome
 - Version: 70

**Comment by SkalskiP** [comment]
Hi @yyuuliang I have verified and of course you're right. The error will be corrected in the near future, as it has high priority.

**Comment by SkalskiP** [comment]
The problem has been solved. The improved version of the application will be available on the production with the next release. Currently, the patches are available on the developer instance: https://develop.makesense.ai/ I would be very grateful if you could verify whether the effect is as intended.

**Comment by yyuuliang** [comment]
I have verified this and it works now, thanks for the fix!

**Comment by SkalskiP** [comment]
Task is for now `In Test` and I will move it to done, after another release.

**Comment by SkalskiP** [comment]
Hi, @yyuuliang! Due to the large amount of bugs that we have managed to fix recently, we decided to make a small release marked with the tag `1.2.1-alpha`. The same applies to this issue, which is now available at https://makesense.ai 

Happy Labelling!
