### ISSUE TITLE
Editing label name after annotation is not working properly

### ISSUE THREAD

**Issue by JimmyJ0ee** [SkalskiP/make-sense#381]
**Describe the bug**
If you want to edit the label name after annotating the images, the label names will not be updated in the downloaded text files.

**To Reproduce**
1. Annotate pictures.
2. Edit label name.
3. Export annotations with yolo format.
4. Check label name in .txt file.

**Expected behavior**
Lable name will be the first-used name and not the updated name.

**Screenshots**
New name:
![image](https://github.com/user-attachments/assets/986f041a-2b4b-48e3-8c2d-f2d415750b6c)
Old name:
![image](https://github.com/user-attachments/assets/9f93c475-8506-4ffe-8fb4-827c8586a5c8)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: Version 131.0.2903.70 (Offizielles Build) (64-Bit)

**Comment by Yuri-Njathi** [comment]
The name in the edit labels popup window isn't the one that appears in annotation file (old name)

For example 
```
labelname1 -> 0
labelname2 -> 1
labelname3 -> 2

```
Example 

![edit-labels](https://github.com/user-attachments/assets/6f8e3258-f067-47ae-a693-257c55fcf7fe)

With labels:

![labels](https://github.com/user-attachments/assets/78fdcee2-d2d3-4b36-8afc-6405d802f86d)

And results into these kind of annotations:
![annotations](https://github.com/user-attachments/assets/4db057bd-fcd8-4d45-8430-ff8a455d594c)


Hope this helps

**Comment by JimmyJ0ee** [comment]
You are right! 
Thanks for explaining. :)

Merry Christmas and a Happy New Year.

**Comment by SkalskiP** [comment]
@Yuri-Njathi, thanks a lot for the help! 🙏🏻

**Comment by Yuri-Njathi** [comment]
Happy to help with open source :)

**Comment by Yuri-Njathi** [comment]
Issue #382 is a good solution to this problem. Please have a look. @SkalskiP
