### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by lukasy09** [SkalskiP/make-sense#43]
**Describe the bug**
While using your app I have noticed the following visual bug(visible in the attached screenshot).
When the browser's download bar is visible and listing downloaded files, the image is partially covering the project's title and two texts are overlapping.
I hope it was helpful for the project

All the best, keep it going, never give up bye :)

**Screenshots**
![visual-bug-paint](https://user-images.githubusercontent.com/23463720/64241520-36ef9300-cf04-11e9-90d1-7539945d5c67.png)

**Comment by SkalskiP** [comment]
Hi @lukasy09 ! Thanks so much for bringing this bug to my attention. We will try to make some fixes in the near future, so that they will be in the next release of the application.

**Comment by SkalskiP** [comment]
@lukasy09  Patch is already on the development version of the application. You can test the changes on https://develop.makesense.ai/

**Comment by SkalskiP** [comment]
Hi, @lukasy09! Due to the large amount of bugs that we have managed to fix recently, we decided to make a small release marked with the tag `1.2.1-alpha`. The same applies to this issue, which is now available at https://makesense.ai 

Happy Labelling!
