### ISSUE TITLE
Faster label writing

### ISSUE THREAD

**Issue by RaccoonForever** [SkalskiP/make-sense#44]
As you seem to answer fast ^^, I've some minor improvements that can make user gain some time.

The first time I tried your application, I wrote my first label then I pressed "Enter", which does nothing I know :D
I was hoping it would add the next label input automatically without pressing the "+" button.

I see two alternatives :
- When the user press enter after writing its label, it adds another label, and autofocus on this new label.
- And/Or when the user press the "+" button to add a new label, then it automatically focus on the label text. It will make the user gain one click and some time.

I know it is a really small feature, but I feel it can be useful !
I hope I was clear enough.

Arthur CG

**Comment by SkalskiP** [comment]
Hi, @RaccoonForever! Indeed, I try to reply quickly and devote as much time as I can to makesense.ai. I admit that these are great ideas. As we are currently working on keyboard shortcuts and the whole mechanism that will manage similar functionality, this is a great time to think about it! As usual, an interesting idea and thanks a lot for sharing it.

**Comment by stobias123** [comment]
@SkalskiP  - anywhere we can see progress on keyboard shortcuts? Using 1-9 to select label, then drawing label and submitting would be a huge improvement. 

Lack of this ability (and thus speed) is the one thing stopping me from using the platform.

**Comment by SkalskiP** [comment]
Hi, @stobias123! Yes, we want to speed up the process of labeling already created rectoms/points and polygons. Probably in a slightly different form than you suggested:
- At the beginning you will draw a rectangle (for example) - its label will be set by default to the last label you added
- When you finish drawing, your focus will be automatically set to label dropdown
- You will be able to either start writing - then the dropdown will open, and the options you will see in it will correspond to the phrase you have started to write
- You will be able to press enter to just open the dropdown
- Using the arrows you will move up and down through the dropdown options
- Being over the option that suits you best, press enter to confirm.
- You press Escape to get out of label selection. And you press Escape again to get out of the right panel and back into the context of the editor.

I think this is the third Task in our pipeline that we're going to do. So this is the near future. Of course, as usual I am open to all contributions and Pull Requests.

**Comment by SkalskiP** [comment]
This issue is already implemented.
