### ISSUE TITLE
freeze when make annotation in max zoom

### ISSUE THREAD

**Issue by bruzat** [SkalskiP/make-sense#58]
**Describe the bug**
The tool is very slow when we zoom in and make bounding box. 

**To Reproduce**
1. upload images
2. zoom max in image
3. make bounding box

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser modzilla firfox
 - Version 69.0 (64 bits)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SkalskiP** [comment]
Hi, @bruzat! I just did some tests on Firefox and it seems that this browser has some problems with rendering larger photos. We will investigate this problem and look for potential optimizations. In the meantime. I already have some ideas for improvements, but they will take some time to implement.

I recommend to switch to Google Chrome - no problems there. Everything runs smoothly.

**Comment by bruzat** [comment]
Thank, it's for make you a feedback. it's very good tools.

**Comment by SkalskiP** [comment]
@bruzat thank you for drawing my attention to this problem and for your kind words.

**Comment by SkalskiP** [comment]
Is it still a problem on FireFox?

**Comment by bruzat** [comment]
I don't know sry
