### ISSUE TITLE
Is it possible to programatically (via Python for example) to upload pictures to Make Sense?

### ISSUE THREAD

**Issue by ahmedbesbes** [SkalskiP/make-sense#69]
This would be part of an automated computer vision project

**Comment by SkalskiP** [comment]
Hi @ahmedbesbes! I am afraid that in order to answer your question properly, I must first understand what it is all about and get to know more details.

**Comment by ahmedbesbes** [comment]
Hello @SkalskiP , 
Sorry, I should've detailed a little bit more. 
So basically what I want to do is create a pipeline a for building an object detection custom dataset.
I imagined this in the following steps:

- fetch images for each class from google api
- store the images locally in appropriate folders (with the right naming for later training)
- automatically upload these images to makesense
- automatically fill in the list of labels to makesense [here ends the automation]
- start labelling the images.

I'm not very proficient in JS so I ended up doing this using Python and Selenium and here's the script I made: https://github.com/ahmedbesbes/dataset-builder

Are you planning to provide an API that allows programatic uploads? This would be helpful for many reasons I guess: 
- no access to a graphic interface for file upload
- dealing with a large number of files spread across many folders...

**Comment by SkalskiP** [comment]
@ahmedbesbes, I looked at your project. I am very pleased that you are planning to develop it around https://www.makesense.ai It is very motivating. 

When it comes to this type of functionality, I have a plan in the future, embed MakeSense inside the Docker and add to it a backend written in Python. I am aware that the application written only and exclusively in JS has its limitations. However, this is a plan for the far future. Certainly not for the next six months. And I will only want to implement it if I manage to find people who would like to contribute.

As for your question. To the best of my knowledge, it is not possible to create such functionality. Allows you to add images to an application from outside but using code. This is not something that can be done in JS.

**Comment by ahmedbesbes** [comment]
@SkalskiP Thank you! Here's a demo: https://youtu.be/qXLvMr9mrP4

I'm looking forward to hearing about new features.

Good work!

**Comment by SkalskiP** [comment]
@ahmedbesbes, today we made the next release. I recommend to see the new functionalities. 

That's great! You surprised me that such a thing is possible at all!!
