### ISSUE TITLE
Polygon Annotation not getting downloaded

### ISSUE THREAD

**Issue by samarthsarin** [SkalskiP/make-sense#72]
Hi,

I am annotating a new image using Polygon Annotations. But when I am downloading the images with Yolo format it's not downloading the .txt file for the image in which I have annotated with polygon boxes.

Thank you

**Comment by SkalskiP** [comment]
Hi, @samarthsarin! In order to understand the problem correctly, I have to ask for a few details. I understand the problem is that you've created polygonal labels, but can't see them in the YOLO downloads?

**Comment by samarthsarin** [comment]
Yes thats the issue

**Comment by SkalskiP** [comment]
Well, it's not an issue. This is very correct behaviour. YOLO format supports rectangles, not polygons. So if you are creating a labelz in the rects tab you can expect that it can be downloaded in YOLO format. If you have created polygons in prompt Export Labels you should select the polygon on the left and exsportport it in VGG format.
