### ISSUE TITLE
Is it possible to use your own YOLOv3 model instead of COCO SSD

### ISSUE THREAD

**Issue by aquadzn** [SkalskiP/make-sense#83]
Hello,

Thank you for your great tool.
I used it to annotate my images for object detection (rectangles) and then trained a YOLOv3 model using the Darknet repo.

Now, is it possible to add my own model, idk by modifying some tensorflow.js (uploading my model to tfhub ?) code in my fork of this repository and use my own model to annotate other images more easily?

thanks

**Comment by SkalskiP** [comment]
Hi, @aquadzn! I understand your model is already converted to TensorFlow?

**Comment by aquadzn** [comment]
> Hi, @aquadzn! I understand your model is already converted to TensorFlow?

no but I could use https://github.com/jinyu121/DW2TF or https://github.com/thtrieu/darkflow to get a .ckpt/.pb file

**Comment by SkalskiP** [comment]
Okay. So I think it's possible. Except, as you can see, the road is not straight. Because you have to go Darknet -> TF -> TF.js. But once you've got that interference inside the tool, it's possible. Only you will have to do a fork repo of course to add it yourself... :/

**Comment by aquadzn** [comment]
ok, does your code somewhere specify the names of the classes or the number of classes for COCO-SSD?

**Comment by SkalskiP** [comment]
No, everything is provided by tensorflow-models/coco-ssd
https://github.com/tensorflow/tfjs-models/blob/master/coco-ssd/src/classes.ts
