### ISSUE TITLE
what should I do if I want to get line annotation?

### ISSUE THREAD

**Issue by animebing** [SkalskiP/make-sense#84]
Thanks for providing such an annotation tool. In my project, I am trying to annotation line, but I find there isn't the option, would you mind telling me what I should modify or add in the current code base to support this idea?

**Comment by SkalskiP** [comment]
@animebing Perhaps you and I could work together? To add such functionality to MakeSense?

**Comment by sreevardhanreddi** [comment]
@SkalskiP I am interested in implementing the line annotation, could you explain how the events and labels are tied together?

**Comment by SkalskiP** [comment]
@sreevardhanreddi would you like to contribute to MakeSense?

**Comment by sreevardhanreddi** [comment]
@SkalskiP Yes!!, I will be glad to contribute

**Comment by SkalskiP** [comment]
Sounds great! Is there any popular format of line labels?

**Comment by sreevardhanreddi** [comment]
I didn't find any, but we can provide the data like this 

in CSV format

label | from point (x,y) | to point (x,y) | image
--- | --- | --- | ---
label name| 1,1 | 2,2 | image name

in JSON format

```

{
  "image": "file name",
  "from": {
    "x": 1,
    "y": 1
  },
  "to": {
    "x": 2,
    "y": 2
  },
  "label": "label name"
}


```

**Comment by SkalskiP** [comment]
@sreevardhanreddi and @animebing I already started work on this feature. I guess it should be on `develop` soon. I'll keep you posted. ;)

**Comment by SkalskiP** [comment]
@sreevardhanreddi and @animebing pull request with line labels is open: https://github.com/SkalskiP/make-sense/pull/89

**Comment by SkalskiP** [comment]
@sreevardhanreddi and @animebing all changes can be tested here: https://develop.makesense.ai

**Comment by SkalskiP** [comment]
@sreevardhanreddi and @animebing, what would be the topical use case for this kind of annotation?

**Comment by sreevardhanreddi** [comment]
@SkalskiP Line annotation can be used for edge/boundary detection
