### ISSUE TITLE
localhost:3000 is not working

### ISSUE THREAD

**Issue by makamkkumar** [SkalskiP/make-sense#85]
npm start

> make-sense@0.1.0 start /Users/makamkirankumar/Downloads/make-sense
> react-scripts start

Attempting to bind to HOST environment variable: x86_64-apple-darwin13.4.0
If this was unintentional, check that you haven't mistakenly set it in your shell.
Learn more here: https://bit.ly/CRA-advanced-config

dyld: lazy symbol binding failed: Symbol not found: _FSEventStreamCreate
  Referenced from: /Users/makamkirankumar/Downloads/make-sense/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: _FSEventStreamCreate
  Referenced from: /Users/makamkirankumar/Downloads/make-sense/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node
  Expected in: flat namespace

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! make-sense@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the make-sense@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/makamkirankumar/.npm/_logs/2020-02-24T17_12_19_308Z-debug.log
(base) Makams-MacBook-Pro:make-sense makamkirankumar$ events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:811:20)
    at process.target.send (internal/child_process.js:682:19)
    at RpcProvider._dispatch (/Users/makamkirankumar/Downloads/make-sense/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:20:17)
    at /Users/makamkirankumar/Downloads/make-sense/node_modules/worker-rpc/lib/RpcProvider.js:107:52
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on process instance at:
    at internal/child_process.js:815:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

**Comment by SkalskiP** [comment]
@makamkkumar Could you give me a version of the npm and node you use? I want to reproduce your environment.

**Comment by alexstorer** [comment]
I get this bug too, just running `create-react-app`.  You can change your environment variables for the first bug here:
https://medium.com/@choy/fixing-create-react-app-when-npm-fails-to-start-because-your-host-environment-variable-is-being-4c8a9fa0b461

I'm not sure what's up with the second bug, but I've tried different versions of the `fsevents` package, and that didn't work.

**Comment by SkalskiP** [comment]
@alexstorer what version of node and nvm do you have?

**Comment by kavyasoni** [comment]
node: v13.10.1
npm: 6.14.2

**Comment by SkalskiP** [comment]
As stated in our `README.md` the suggested environment is npm `6.x.x` and node.js `v11.x.x`. Could you set up this environment and then run MakeSense locally?

**Comment by satkhan** [comment]
For 

> x86_64-apple-darwin13.4.0 bind issue

just append the entry of localhost (if present) in /etc/hosts for 
**127.0.0.1    localhost   x86_64-apple-darwin13.4.0**

**Comment by prashastha-mudannayake** [comment]
I got the same error, someone  suggested to add HOST="localhost" to the `.bash_profile` and `source ~/.bash_profile` to load it back, but it didn't work

**Comment by prashastha-mudannayake** [comment]
I found solution. Remove `/my-app/node_modules/webpack-dev-server/fsevents`. The `npm start` should do it.

**Comment by maxiperaltaaok** [comment]
@prashastham what command goes before  that..../my-app/node_modules/webpack-dev-server/fsevents

**Comment by prashastham** [comment]
On Linux or macOS `rm -rf` should work, in windows command prompt `rmdir` should work
