### ISSUE TITLE
COCO Format suppport

### ISSUE THREAD

**Issue by herruli** [SkalskiP/make-sense#86]
Just asking whether it will support COCO format in the near future? As Detectron2 is supporting COCO format.

**Comment by SkalskiP** [comment]
Hello @herruli :) I think so, but which type of label would you like to have exported? Rects or something else?

**Comment by ericman93** [comment]
Coco for polygons will be great!

**Comment by SkalskiP** [comment]
@ericman93 I'll take that into account when prioritizing tasks for the next release. ;)

**Comment by SkalskiP** [comment]
@ericman93 and @herruli PR is open #107. Support for COCO export for polygons soon to be added.
