### ISSUE TITLE
How to save my work

### ISSUE THREAD

**Issue by deep-learning-newbie** [SkalskiP/make-sense#99]
**Is your feature request related to a problem? Please describe.**
I can't save my work. My dataset contains more them 1K images - it is impossible to annotate them in a day therefore I'd like to save my work and then return to one the next day - but I can't find something like Save or project, or something which allows me to return to my work which is already done  

**Describe the solution you'd like**
Any mechanism which allows me to save my work

**Comment by SkalskiP** [comment]
Hi @deep-learning-newbie! Unfortunately, that functionality. is not yet implemented in MakeSense.

**Comment by SkalskiP** [comment]
This issue is duplicate of #32.
